month-8 start
RomanF89/react-burger pull request #3
Opened 2023-02-01 23:58 UTC by RomanF89

2023-02-02 03:17 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец!**

- Сборка и запуск проекта выполняются без ошибок;
- Используется контекст;

### **Но есть несколько замечаний, которые нужно исправить:**

- Нужно очистить проект от лишних файлов, которые остались при инициализации create-react-app.

  - App.test.tsx

- В компоненте App-header требуется поправить семантику, переделать div в ссылки.

- В запросе `/orders` нужно чтобы id у булок были в начале и в конце массива: <https://disk.yandex.com/i/PMv9EKmzbxXeRw>;

- по чек-листу файл контекста должен быть в папке `/services`;

- Исправьте ошибку в консоли при открытии модального окна: <https://disk.yandex.com/i/iTiUQc9wRjQbSQ>;

- Нужно поменять формат файла `.js` на `.jsx` у всех файлах, где используется jsx разметка.

### **Сделает код лучше:**

- При клике на таб скролить список ингредиентов к нужному разделу;

- Перед отправкой работы убедитесь в том, что весь неиспользуемый код удален.

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: <https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders>

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

#### **Хочу напомнить, что работа может быть принята, только после исправления всех "Надо исправить". Перед отправкой на ревью, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12).**

2023-02-02 03:17 UTC, ArslanDev666 commented on src/components/App/App.js
> +  const [orderData, setOrderData] = React.useState({});
**Надо исправить:**

Если значения нет, то нужно использовать null, а не пустой объект.

2023-02-02 03:17 UTC, ArslanDev666 commented on src/components/App/App.js
>    const [data, setData] = React.useState('');
**Надо исправить:**

В начальном значении тут должен быть пустой массив, а не строка.

2023-02-02 03:17 UTC, ArslanDev666 commented on src/components/App/App.js
>      api.getData()
**Можно лучше:**

Лучше занести функцию в useEffect.

2023-02-02 03:17 UTC, ArslanDev666 commented on src/components/App/App.js
> +          <AppContext.Provider value={{data, orderData, setOrderData, setError}}>
**Можно лучше:**

burger-ingredients можно тоже обернуть в контекст, и использовать data.

2023-02-02 03:17 UTC, ArslanDev666 commented on src/components/BurgerConstructor/BurgerConstructor.js
>    const otherBurgerItems = data.filter((filteredItem) => filteredItem.type === 'main' || filteredItem.type === 'sauce');
**Можно лучше:**

оберните в useMemo)

2023-02-02 03:17 UTC, ArslanDev666 commented on src/components/BurgerConstructor/BurgerConstructor.js
> +  },[]);
**Можно лучше:**

Лучше собирать эти данные в функции orderClick.

2023-02-02 03:17 UTC, ArslanDev666 commented on src/components/BurgerConstructor/BurgerConstructor.js
>    const [modalData, setModalData] = React.useState({});
**Надо исправить:**

Если значения нет, то нужно использовать null, а не пустой объект.

2023-02-02 03:17 UTC, ArslanDev666 commented on src/components/BurgerConstructor/BurgerConstructor.js
>    function OrderClick () {
**Надо исправить:**

функции принято называть через camelCase.

2023-02-02 03:17 UTC, ArslanDev666 commented on src/components/BurgerConstructor/BurgerConstructor.js
> +    const otherIngredientsPrice = otherBurgerItems.reduce(function (previousValue, value) {
**Можно лучше:** 

Цена считается неправильно, вы не учитываете, что у нас 2 булки, а не 1.

2023-02-02 03:17 UTC, ArslanDev666 commented on src/components/BurgerConstructor/BurgerConstructor.js
>      </Modal>
**Надо исправить**

не нужно передавать условие открытия в попап и размещать логику открытия там. Рендерите компонент попапа только, если он открыт, используя для этого условный рендеринг

```js
{isOpen && (
    компонент открываемого попапа
)}
```

А также не нужно выводить контент через условия. А то если у вас будет оч много вариаций попапа, будет оч много условий. Просто используйте нужный попап в соответствующем компоненте (`burger-ingredients`  и `burger-constructor`)

2023-02-03 20:52 UTC, RomanF89 commented on src/components/BurgerConstructor/BurgerConstructor.js
>      </Modal>
Здравствуйте! По поводу этого замечания. В моих компонентах (burger-ingredients и burger-constructor) используется Modal с нужным children , а в burger-constructor стоит условный рендер через поле type , так как в этом компоненте у меня модалка и с информацией об ингредиенте и с информацией по заказу.

2023-02-04 04:52 UTC, ArslanDev666 commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +        {isModalOpen && modalType === 'ingredient' ? <IngredientDetails data={modalData} /> : (isModalOpen && <OrderDetails orderData={orderData} />)}
**Можно лучше:**

Кажется, вы тут переборщили с условиями)

```js
{isModalOpen && (
  <Modal isOpen={isModalOpen} handleClose={handleClose}>
    {modalType === "ingredient" ? (
      <IngredientDetails data={modalData} />
    ) : (
      <OrderDetails orderData={orderData} />
    )}
  </Modal>
)}
```

Также, всё таки попытайтесь избавится от пропса `isOpen` в компоненте `modal`.

2023-02-04 04:52 UTC, ArslanDev666 commented on src/components/BurgerConstructor/BurgerConstructor.js
>      </Modal>
Понял)) написал в комментарии, как можно чуть проще написать

2023-02-04 04:53 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец! Работа принята, удачи в дальнейшем обучении!**

- Все замечания с прошлого ревью были исправлены.

### **Рекомендую исправить:**

- В запросе `/orders` нужно чтобы id у булок были в начале и в конце массива: <https://disk.yandex.com/i/8npHz0oL2uRS1w>;

2023-02-04 13:35 UTC, merged