first commit
RomanF89/react-burger pull request #6
Opened 2023-07-29 18:38 UTC by RomanF89

2023-07-29 20:21 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- Реализовали универсальный веб-сокет
- Сокеты открываются и закрываются согласно брифу

Необходимо исправить:
- В карточке заказа необходимо указывать количество ингредиентов. Повторяющиеся ингредиенты необходимо подсчитывать и указывать их количество, а не дублировать.

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-07-29 20:21 UTC, andryxxa93 commented on src/components/App/App.jsx
>          <ProtectedRouteAuthorized exact path={"/login"}>
**Можно лучше**
Роуты желательно записывать в константы - так проще их менять и сложнее ошибиться при использовании в нескольких местах.

2023-07-29 20:21 UTC, andryxxa93 commented on src/middleware/socket-middleware.js
> +              socket.onmessage = event => {
**Можно лучше**
Необходимо добавить проверку при получении сообщения от сокета. Eсли токен протух и приходит поле message 'Invalid or missing token' то его необходимо обновить через refreshToken.

2023-07-29 20:21 UTC, andryxxa93 commented on src/components/ProfileNavigation/ProfileNavigation.jsx
> +  const { data } = useSelector(store => ({
**Можно лучше**
Хорошая практика - передавать в useSelector не анонимную, а именованную функцию. Это позволит избежать лишних вызовов useSelector. 
https://www.youtube.com/watch?v=SVG-x-4BQic

2023-07-29 20:21 UTC, andryxxa93 commented on src/components/OrderInfo/OrderInfo.jsx
> +      .catch((err) => console.log(err))
**Можно лучше**
хорошо, что обрабатывается ошибка запроса к фзш api, но можно сделать еще лучше - сохранять в state и показывать пользователю ошибку в интерфейсе, чтобы он понимал что происходит

2023-07-29 20:21 UTC, andryxxa93 commented on src/components/App/App.jsx
> +      )}
**Можно лучше**
Не обязательно каждый такой роут оборачивать в отдельный `switch` - можно в один поместить сразу несколько

2023-07-29 20:21 UTC, andryxxa93 commented on src/components/FeedCard/FeedCard.jsx
> +  const price = currentIngredients.reduce(function (previousValue, value) {
**Можно лучше**
Сложные операции желательно оборачивать в хук `useMemo` чтобы избежать ненужных выполнений. 
https://ru.reactjs.org/docs/hooks-reference.html#usememo

2023-07-30 16:31 UTC, RomanF89 commented on src/components/FeedCard/FeedCard.jsx
> +  const price = currentIngredients.reduce(function (previousValue, value) {
Здравствуйте , на useMemo при рассчете price ругается линтер , видимо из-за объявления  let currentIngredients = []; ранее , я так и не разобрался как решить эту проблему.

2023-07-31 05:51 UTC, andryxxa93 commented on src/components/FeedCard/FeedCard.jsx
> +  const price = currentIngredients.reduce(function (previousValue, value) {
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-09-07 15:36 UTC, merged